vich_uploader:
    db_driver: orm

    mappings:
        fichiers:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        #medecin:
        #    uri_prefix: /uploads/medecin/images
        #    upload_destination: '%kernel.project_dir%/public/uploads/medecin/images'
        #    namer: Vich\UploaderBundle\Naming\OrignameNamer